-- noinspection SqlResolveForFile

-- DROP TABLE LINEAGE_TEST_PARAMS;
-- DROP TABLE LINEAGE_TEST_CUSTOMER;
-- DROP TABLE LINEAGE_TEST_PRODUCT;
-- DROP TABLE LINEAGE_TEST_ORDER;
-- DROP TABLE LINEAGE_TEST_ORDER_ITEM;

-- =========================================================
-- PARAMS
-- =========================================================
CREATE TABLE LINEAGE_TEST_PARAMS (
  PARAMS_NAME VARCHAR2(30) NOT NULL,
  CURRENCY_CD CHAR(3 CHAR) DEFAULT 'EUR' NOT NULL,
  DT_FROM     DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  DT_TO       DATE DEFAULT TRUNC(SYSDATE) NOT NULL
);

-- =========================================================
-- CUSTOMER
-- =========================================================
CREATE TABLE LINEAGE_TEST_CUSTOMER (
  CUSTOMER_ID NUMBER,
  CUSTOMER_NO VARCHAR2(30) NOT NULL,
  FULL_NAME VARCHAR2(200) NOT NULL,
  EMAIL VARCHAR2(320),
  PHONE VARCHAR2(30),
  STATUS_CD VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_LINEAGE_TEST_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT UK_LINEAGE_TEST_CUSTOMER_NO UNIQUE (CUSTOMER_NO),
  CONSTRAINT CK_LINEAGE_TEST_CUSTOMER_STATUS CHECK (STATUS_CD IN ('ACTIVE','INACTIVE'))
);
CREATE INDEX IX_LINEAGE_TEST_CUSTOMER_EMAIL ON LINEAGE_TEST_CUSTOMER (EMAIL);

COMMENT ON TABLE LINEAGE_TEST_CUSTOMER IS 'Customers master data (test)';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.CUSTOMER_ID IS 'Surrogate key of the customer';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.CUSTOMER_NO IS 'Business customer number';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.FULL_NAME IS 'Full customer name';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.EMAIL IS 'Email address';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.PHONE IS 'Phone number';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.STATUS_CD IS 'Customer status code (ACTIVE/INACTIVE)';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.CREATED_AT IS 'Row creation timestamp';
COMMENT ON COLUMN LINEAGE_TEST_CUSTOMER.UPDATED_AT IS 'Row last update timestamp';

-- =========================================================
-- PRODUCT
-- =========================================================
CREATE TABLE LINEAGE_TEST_PRODUCT (
  PRODUCT_ID NUMBER,
  SKU VARCHAR2(50) NOT NULL,
  PRODUCT_NAME VARCHAR2(200) NOT NULL,
  CATEGORY VARCHAR2(100),
  LIST_PRICE NUMBER(12,2) NOT NULL,
  IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_LINEAGE_TEST_PRODUCT PRIMARY KEY (PRODUCT_ID),
  CONSTRAINT UK_LINEAGE_TEST_PRODUCT_SKU UNIQUE (SKU),
  CONSTRAINT CK_LINEAGE_TEST_PRODUCT_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CK_LINEAGE_TEST_PRODUCT_PRICE CHECK (LIST_PRICE >= 0)
);
CREATE INDEX IX_LINEAGE_TEST_PRODUCT_CAT ON LINEAGE_TEST_PRODUCT (CATEGORY);

COMMENT ON TABLE LINEAGE_TEST_PRODUCT IS 'Products catalog (test)';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.PRODUCT_ID IS 'Surrogate key of the product';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.SKU IS 'Stock keeping unit';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.PRODUCT_NAME IS 'Product name';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.CATEGORY IS 'Product category';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.LIST_PRICE IS 'List price';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.IS_ACTIVE IS 'Active flag (Y/N)';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.CREATED_AT IS 'Row creation timestamp';
COMMENT ON COLUMN LINEAGE_TEST_PRODUCT.UPDATED_AT IS 'Row last update timestamp';

-- =========================================================
-- PRODUCT VIEW
-- =========================================================
CREATE VIEW DWHKIT.LINEAGE_TEST_PRODUCT_V AS
SELECT *
FROM DWHKIT.LINEAGE_TEST_PRODUCT;

COMMENT ON TABLE LINEAGE_TEST_PRODUCT_V IS 'Products catalog view (test)';

-- =========================================================
-- ORDER
-- =========================================================
CREATE TABLE LINEAGE_TEST_ORDER (
  ORDER_ID NUMBER,
  ORDER_NO VARCHAR2(30) NOT NULL,
  CUSTOMER_ID NUMBER NOT NULL,
  ORDER_DT DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  STATUS_CD VARCHAR2(20) DEFAULT 'NEW' NOT NULL,
  CURRENCY_CD CHAR(3) DEFAULT 'EUR' NOT NULL,
  BILLING_NAME VARCHAR2(200),
  BILLING_STREET1 VARCHAR2(200),
  BILLING_CITY VARCHAR2(120),
  BILLING_POSTAL_CODE VARCHAR2(20),
  BILLING_COUNTRY_CD CHAR(2),
  SHIPPING_NAME VARCHAR2(200),
  SHIPPING_STREET1 VARCHAR2(200),
  SHIPPING_STREET2 VARCHAR2(200),
  SHIPPING_CITY VARCHAR2(120),
  SHIPPING_POSTAL_CODE VARCHAR2(20),
  SHIPPING_COUNTRY_CD CHAR(2),
  PAYMENT_METHOD VARCHAR2(30),
  PAYMENT_TXN_ID VARCHAR2(80),
  PAID_AT TIMESTAMP,
  SHIPPING_METHOD VARCHAR2(30),
  TRACKING_NO VARCHAR2(60),
  SHIPPED_AT TIMESTAMP,
  DELIVERED_AT TIMESTAMP,
  SUBTOTAL_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TAX_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
  SHIPPING_COST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_DISCOUNT_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
  CHANNEL_CD VARCHAR2(20) DEFAULT 'WEB' NOT NULL,
  COUPON_CD VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_LINEAGE_TEST_ORDER PRIMARY KEY (ORDER_ID),
  CONSTRAINT UK_LINEAGE_TEST_ORDER_NO UNIQUE (ORDER_NO),
  CONSTRAINT FK_LINEAGE_TEST_ORDER_CUST FOREIGN KEY (CUSTOMER_ID)
    REFERENCES LINEAGE_TEST_CUSTOMER (CUSTOMER_ID),
  CONSTRAINT CK_LINEAGE_TEST_ORDER_STATUS CHECK (STATUS_CD IN ('NEW','PAID','SHIPPED','CANCELLED')),
  CONSTRAINT CK_LINEAGE_TEST_ORDER_CURR CHECK (REGEXP_LIKE(CURRENCY_CD, '^[A-Z]{3}$')),
  CONSTRAINT CK_LINEAGE_TEST_ORDER_CHANNEL CHECK (CHANNEL_CD IN ('WEB','MOBILE','STORE','API')),
  CONSTRAINT CK_LINEAGE_TEST_ORDER_PAYMETHOD CHECK (PAYMENT_METHOD IS NULL OR PAYMENT_METHOD IN ('CARD','SEPA','PAYPAL','BANK_TRANSFER')),
  CONSTRAINT CK_LINEAGE_TEST_ORDER_SHIPMETHOD CHECK (SHIPPING_METHOD IS NULL OR SHIPPING_METHOD IN ('STANDARD','EXPRESS','PICKUP'))
);
CREATE INDEX IX_LINEAGE_TEST_ORDER_CUST ON LINEAGE_TEST_ORDER (CUSTOMER_ID);
CREATE INDEX IX_LINEAGE_TEST_ORDER_DT ON LINEAGE_TEST_ORDER (ORDER_DT);

COMMENT ON TABLE LINEAGE_TEST_ORDER IS 'Customer orders (test)';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.ORDER_ID IS 'Surrogate key of the order';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.ORDER_NO IS 'Business order number';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.CUSTOMER_ID IS 'Customer reference';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.ORDER_DT IS 'Order date';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.STATUS_CD IS 'Order status code';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.CURRENCY_CD IS 'ISO currency code';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.BILLING_NAME IS 'Billing contact name';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.BILLING_STREET1 IS 'Billing street and house number';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.BILLING_CITY IS 'Billing city';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.BILLING_POSTAL_CODE IS 'Billing postal code';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.BILLING_COUNTRY_CD IS 'Billing country code (ISO-3166-1 alpha-2)';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_NAME IS 'Shipping contact name';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_STREET1 IS 'Shipping street and house number';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_STREET2 IS 'Shipping address line 2';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_CITY IS 'Shipping city';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_POSTAL_CODE IS 'Shipping postal code';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_COUNTRY_CD IS 'Shipping country code (ISO-3166-1 alpha-2)';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.PAYMENT_METHOD IS 'Payment method';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.PAYMENT_TXN_ID IS 'External payment transaction id';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.PAID_AT IS 'Payment timestamp';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_METHOD IS 'Shipping method';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.TRACKING_NO IS 'Shipment tracking number';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPED_AT IS 'Shipment timestamp';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.DELIVERED_AT IS 'Delivery timestamp';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SUBTOTAL_AMT IS 'Subtotal amount (after line discounts, before tax/shipping)';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.TAX_AMT IS 'Tax amount';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.SHIPPING_COST IS 'Shipping cost';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.TOTAL_DISCOUNT_AMT IS 'Total discount amount';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.TOTAL_AMT IS 'Total order amount';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.CHANNEL_CD IS 'Sales channel';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.COUPON_CD IS 'Coupon code';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.CREATED_AT IS 'Row creation timestamp';
COMMENT ON COLUMN LINEAGE_TEST_ORDER.UPDATED_AT IS 'Row last update timestamp';

-- =========================================================
-- ORDER VIEW
-- =========================================================
CREATE VIEW DWHKIT.LINEAGE_TEST_ORDER_V AS
SELECT *
FROM DWHKIT.LINEAGE_TEST_ORDER;

-- =========================================================
-- ORDER_ITEM
-- =========================================================
CREATE TABLE LINEAGE_TEST_ORDER_ITEM (
  ORDER_ITEM_ID NUMBER,
  ORDER_ID NUMBER NOT NULL,
  LINE_NO NUMBER(6) NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  QTY NUMBER(12,3) NOT NULL,
  UNIT_PRICE NUMBER(12,2) NOT NULL,
  DISCOUNT_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_LINEAGE_TEST_ORDER_ITEM PRIMARY KEY (ORDER_ITEM_ID),
  CONSTRAINT UK_LINEAGE_TEST_ORDER_ITEM_LINE UNIQUE (ORDER_ID, LINE_NO),
  CONSTRAINT FK_LINEAGE_TEST_OI_ORDER FOREIGN KEY (ORDER_ID)
    REFERENCES LINEAGE_TEST_ORDER (ORDER_ID),
  CONSTRAINT FK_LINEAGE_TEST_OI_PROD FOREIGN KEY (PRODUCT_ID)
    REFERENCES LINEAGE_TEST_PRODUCT (PRODUCT_ID),
  CONSTRAINT CK_LINEAGE_TEST_OI_QTY CHECK (QTY > 0),
  CONSTRAINT CK_LINEAGE_TEST_OI_PRICE CHECK (UNIT_PRICE >= 0),
  CONSTRAINT CK_LINEAGE_TEST_OI_DISC CHECK (DISCOUNT_AMT >= 0)
);
CREATE INDEX IX_LINEAGE_TEST_OI_ORDER ON LINEAGE_TEST_ORDER_ITEM (ORDER_ID);
CREATE INDEX IX_LINEAGE_TEST_OI_PROD ON LINEAGE_TEST_ORDER_ITEM (PRODUCT_ID);

COMMENT ON TABLE LINEAGE_TEST_ORDER_ITEM IS 'Order line items (test)';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.ORDER_ITEM_ID IS 'Surrogate key of the order line';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.ORDER_ID IS 'Order reference';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.LINE_NO IS 'Line number within the order';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.PRODUCT_ID IS 'Product reference';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.QTY IS 'Ordered quantity';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.UNIT_PRICE IS 'Unit price';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.DISCOUNT_AMT IS 'Line discount amount';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.CREATED_AT IS 'Row creation timestamp';
COMMENT ON COLUMN LINEAGE_TEST_ORDER_ITEM.UPDATED_AT IS 'Row last update timestamp';

